name: 'Re-deploy Docker Containers'
description: 'Re-deploy running docker containers'
author: 'Anthony LaForgia'

runs:
  using: 'composite'
  
  steps: 
    - name: Log Info
      shell: bash
      run: docker container ls --format 'table {{.ID}}{{ .Image }}' | tail -n +2 > containers.log

    - name: Rebuild Containers
      shell: bash
      run: | 
        for container in $(cat containers.log) 
          do 
            docker container stop $(echo $container | cut -c -12)
            docker run -d $(echo $container | cut -c 13-)
          done
          
    - name: Tidy Up
      shell: bash
      run: |
        rm *.log
        docker container prune -f

branding:
  icon: 'x'
  color: 'gray-dark'
